[build]
  base = "/"
  command = "npm run build"
  publish = "apps/landing/dist"
  functions = "apps/landing/netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
